version: '3.5'

services:
  latest:
    build: ./py37
    image: ftopal/machine-learning:latest
  py37:
    build: ./py37
    image: ftopal/machine-learning:py37
  py37-cuda10.2:
    build: ./py37-cuda10.2
    image: ftopal/machine-learning:py37-cuda10.2
  keplergl:
    build: ./keplergl
    image: ftopal/keplergl:latest
  spark-245:
   build: ./spark
   image: ftopal/spark:2.4.5
  spark-latest:
     build: ./spark
     image: ftopal/spark:latest
